export const CURRENT_TOS_VERSION = Symbol('CURRENT_TOS_VERSION');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const JWT_ACCESS_EXPIRES_IN_SECONDS = Symbol(
  'JWT_ACCESS_EXPIRES_IN_SECONDS',
);
