export const CURRENT_TOS_VERSION = Symbol('CURRENT_TOS_VERSION');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');
export const REFRESH_TOKEN_HASHER = Symbol('REFRESH_TOKEN_HASHER');
export const AUTH_TOKEN_ISSUER = Symbol('AUTH_TOKEN_ISSUER');
export const JWT_ACCESS_EXPIRES_IN_SECONDS = Symbol(
  'JWT_ACCESS_EXPIRES_IN_SECONDS',
);
export const JWT_REFRESH_EXPIRES_IN_SECONDS = Symbol(
  'JWT_REFRESH_EXPIRES_IN_SECONDS',
);
